name: Full Release with Docs

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build AppImage
        run: |
          chmod +x build_appimage.sh
          ./build_appimage.sh

      - name: Generate .zsync
        run: |
          chmod +x generate_zsync.sh
          ./generate_zsync.sh

      - name: Upload AppImage and zsync to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CryptoAlert*.AppImage
            *.zsync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        run: |
          echo "## ${{ github.ref_name }} - $(date +'%Y-%m-%d')" >> CHANGELOG.md
          echo "- Automated release from CI" >> CHANGELOG.md

      - name: Commit and push updated CHANGELOG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for ${{ github.ref_name }}"
          git push